version: '3.1'
name: "bellatrix"
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      # MONGO_INITDB_DATABASE: bellatrix
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodb:/data/mongo
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    restart: unless-stopped
volumes:
  mongodb: